import { run } from './../utils/endpointRunner'
import { work } from './../utils/endpointWorker'
import { ENDPOINTS } from './../constants' // eslint-disable-line no-unused-vars

const nba = run(work)

export const allPlayers = (query, cb) => nba('ALL_PLAYERS', query, cb)
export const assistTracker = (query, cb) => nba('ASSIST_TRACKER', query, cb)
export const defenseHub = (query, cb) => nba('DEFENSE_HUB', query, cb)
export const draftCombine = (query, cb) => nba('DRAFT_COMBINE', query, cb)
export const draftHistory = (query, cb) => nba('DRAFT_HISTORY', query, cb)
export const franchiseHistory = (query, cb) => nba('FRANCHISE_HISTORY', query, cb)
export const franchiseLeaders = (query, cb) => nba('FRANCHISE_LEADERS', query, cb)
export const homepage = (query, cb) => nba('HOMEPAGE', query, cb)
export const leagueGamelog = (query, cb) => nba('LEAGUE_GAMELOG', query, cb)
export const leagueLeaders = (query, cb) => nba('LEAGUE_LEADERS', query, cb)
export const playerAwards = (query, cb) => nba('PLAYER_AWARDS', query, cb)
export const playerBioStats = (query, cb) => nba('PLAYER_BIO_STATS', query, cb)
export const playerCareerStats = (query, cb) => nba('PLAYER_CAREER_STATS', query, cb)
export const playerClutchStats = (query, cb) => nba('PLAYER_CLUTCH_STATS', query, cb)
export const playerCompare = (query, cb) => nba('PLAYER_COMPARE', query, cb)
export const playerDefenseStats = (query, cb) => nba('PLAYER_DEFENSE_STATS', query, cb)
export const playerGamelog = (query, cb) => nba('PLAYER_GAMELOG', query, cb)
export const playerGeneralStats = (query, cb) => nba('PLAYER_GENERAL_STATS', query, cb)
export const playerHustleLeaders = (query, cb) => nba('PLAYER_HUSTLE_STATS_LEADERS', query, cb)
export const playerHustleStats = (query, cb) => nba('PLAYER_HUSTLE_STATS', query, cb)
export const playerInfo = (query, cb) => nba('PLAYER_INFO', query, cb)
export const playerProfile = (query, cb) => nba('PLAYER_PROFILE', query, cb)
export const playerShotLocationStats = (query, cb) => nba('PLAYER_SHOT_LOCATION_STATS', query, cb)
export const playerShotStats = (query, cb) => nba('PLAYER_SHOT_STATS', query, cb)
export const scoreboard = (query, cb) => nba('SCOREBOARD', query, cb)
export const teamClutchStats = (query, cb) => nba('TEAM_CLUTCH_STATS', query, cb)
export const teamDefenseStats = (query, cb) => nba('TEAM_DEFENSE_STATS', query, cb)
export const teamDetails = (query, cb) => nba('TEAM_DETAILS', query, cb)
export const teamGamelog = (query, cb) => nba('TEAM_GAMELOG', query, cb)
export const teamGeneralStats = (query, cb) => nba('TEAM_GENERAL_STATS', query, cb)
export const teamHustleLeaders = (query, cb) => nba('TEAM_HUSTLE_STATS_LEADERS', query, cb)
export const teamHustleStats = (query, cb) => nba('TEAM_HUSTLE_STATS', query, cb)
export const teamInfo = (query, cb) => nba('TEAM_INFO', query, cb)
export const teamLineups = (query, cb) => nba('TEAM_LINEUPS', query, cb)
export const teamOnOffCourt = (query, cb) => nba('TEAM_ON_OFF_COURT', query, cb)
export const teamPassTracking = (query, cb) => nba('TEAM_PASS_TRACKING_STATS', query, cb)
export const teamPlayers = (query, cb) => nba('TEAM_PLAYERS', query, cb)
export const teamReboundTracking = (query, cb) => nba('TEAM_REB_TRACKING_STATS', query, cb)
export const teamRoster = (query, cb) => nba('TEAM_ROSTER', query, cb)
export const teamShotLocationStats = (query, cb) => nba('TEAM_SHOT_LOCATION_STATS', query, cb)
export const teamShotStats = (query, cb) => nba('TEAM_SHOT_STATS', query, cb)
export const teamShotTracking = (query, cb) => nba('TEAM_SHOT_TRACKING_STATS', query, cb)
export const teamSplits = (query, cb) => nba('TEAM_SPLITS', query, cb)
export const teamYearlyStats = (query, cb) => nba('TEAM_YEARLY_STATS', query, cb)
export const trackingStats = (query, cb) => nba('TRACKING_STATS', query, cb)
